import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/": [
    {
      icon: "computer",
      text: "一、计算机基础",
      collapsible: true,
      prefix: "fundamental/",
      children: [
        {
          icon: "network",
          text: "计网",
          prefix: "network/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "os",
          text: "操作系统",
          prefix: "operating_system/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "pattern",
          text: "设计模式",
          prefix: "design_atterns/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "linux",
          text: "linux",
          prefix: "linux/",
          children: "structure",
          collapsible: true,
        }
      ]
    },
    {
      icon: "vscode",
      text: "二、前端",
      prefix: "frontend",
      children: "structure",
      collapsible: true,
    },
    {
      icon: "java",
      text: "三、Java",
      collapsible: true,
      prefix: "Java/",
      children: [
        {
          icon: "basis",
          text: "基础",
          prefix: "basic",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "collections",
          text: "集合",
          prefix: "collections",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "concurrent",
          text: "并发",
          prefix: "concurrent",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "jvm",
          text: "JVM",
          prefix: "jvm",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "redis",
          text: "Redis",
          prefix: "redis",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "mysql",
          text: "Mysql",
          prefix: "mysql",
          children: "structure",
          collapsible: true,
        },
        // {
        //   icon: "leetcode",
        //   text: "LeetCode刷题",
        //   prefix: "leetcode",
        //   children: "structure",
        //   collapsible: true,
        // },
        {
          icon: "git",
          text: "Git",
          prefix: "git",
          children: "structure",
          collapsible: true,
        },
      ]
    },
    {
      icon: "rust",
      text: "四、Rust",
      prefix: "rust",
      children: "structure",
      collapsible: true,
    },
    {
      icon: "computer",
      text: "五、AI",
      collapsible: true,
      prefix: "ai/",
      children: [
        {
          icon: "basis",
          text: "基础概念",
          prefix: "basic/",
          collapsible: true,
          children: [
            { icon: "basis", text: "机器学习入门", prefix: "01-机器学习入门/", children: "structure", collapsible: true },
            { icon: "spring", text: "深度学习基础", prefix: "02-深度学习基础/", children: "structure", collapsible: true },
            { icon: "pattern", text: "常用数学", prefix: "03-常用数学/", children: "structure", collapsible: true },
            { icon: "scaffold", text: "基本术语", prefix: "04-基本术语/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "framework",
          text: "大模型与 LLM",
          prefix: "llm/",
          collapsible: true,
          children: [
            { icon: "framework", text: "Transformer", prefix: "01-Transformer/", children: "structure", collapsible: true },
            { icon: "vscode", text: "GPT 与 Claude", prefix: "02-GPT与Claude/", children: "structure", collapsible: true },
            { icon: "discover", text: "上下文与幻觉", prefix: "03-上下文与幻觉/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "experience",
          text: "Prompt 工程",
          prefix: "prompt/",
          collapsible: true,
          children: [
            { icon: "scaffold", text: "提示模板", prefix: "01-提示模板/", children: "structure", collapsible: true },
            { icon: "collections", text: "Few-shot", prefix: "02-Few-shot/", children: "structure", collapsible: true },
            { icon: "discover", text: "CoT", prefix: "03-CoT/", children: "structure", collapsible: true },
            { icon: "pattern", text: "角色设定", prefix: "04-角色设定/", children: "structure", collapsible: true },
            { icon: "network", text: "输出格式控制", prefix: "05-输出格式控制/", children: "structure", collapsible: true },
            { icon: "bug", text: "常见坑", prefix: "06-常见坑/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "discover",
          text: "RAG 与检索",
          prefix: "rag/",
          collapsible: true,
          children: [
            { icon: "scaffold", text: "文档切片", prefix: "01-文档切片/", children: "structure", collapsible: true },
            { icon: "redis", text: "向量库（Milvus/FAISS 等）", prefix: "02-向量库/", children: "structure", collapsible: true },
            { icon: "gateway", text: "检索策略", prefix: "03-检索策略/", children: "structure", collapsible: true },
            { icon: "git", text: "HyDE", prefix: "04-HyDE/", children: "structure", collapsible: true },
            { icon: "microservices", text: "多路召回", prefix: "05-多路召回/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "microservices",
          text: "Agent / 智能体",
          prefix: "agent/",
          collapsible: true,
          children: [
            { icon: "rocket", text: "ReAct", prefix: "01-ReAct/", children: "structure", collapsible: true },
            { icon: "vscode", text: "Tool Use", prefix: "02-Tool-Use/", children: "structure", collapsible: true },
            { icon: "microservices", text: "多 Agent", prefix: "03-多Agent/", children: "structure", collapsible: true },
            { icon: "framework", text: "LangGraph", prefix: "04-LangGraph/", children: "structure", collapsible: true },
            { icon: "project3", text: "实际案例", prefix: "05-实际案例/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "project3",
          text: "应用与落地",
          prefix: "application/",
          collapsible: true,
          children: [
            { icon: "pattern", text: "模型选型", prefix: "01-模型选型/", children: "structure", collapsible: true },
            { icon: "vscode", text: "API 调用", prefix: "02-API调用/", children: "structure", collapsible: true },
            { icon: "git", text: "LangChain 与 LlamaIndex", prefix: "03-LangChain与LlamaIndex/", children: "structure", collapsible: true },
            { icon: "framework", text: "与现有项目结合", prefix: "04-与现有项目结合/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "vscode",
          text: "工具与平台",
          prefix: "tools/",
          collapsible: true,
          children: [
            { icon: "opensource", text: "OpenAI API", prefix: "01-OpenAI-API/", children: "structure", collapsible: true },
            { icon: "discover", text: "Hugging Face", prefix: "02-Hugging-Face/", children: "structure", collapsible: true },
            { icon: "docker", text: "Ollama 与本地部署", prefix: "03-Ollama与本地部署/", children: "structure", collapsible: true },
            { icon: "redis", text: "向量库选型", prefix: "04-向量库选型/", children: "structure", collapsible: true },
            { icon: "rocket", text: "评测与监控", prefix: "05-评测与监控/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "scaffold",
          text: "模型微调与训练",
          prefix: "finetuning/",
          collapsible: true,
          children: [
            { icon: "pattern", text: "LoRA / QLoRA", prefix: "01-LoRA与QLoRA/", children: "structure", collapsible: true },
            { icon: "basis", text: "全量微调", prefix: "02-全量微调/", children: "structure", collapsible: true },
            { icon: "experience", text: "数据构造", prefix: "03-数据构造/", children: "structure", collapsible: true },
            { icon: "rocket", text: "评估与迭代", prefix: "04-评估与迭代/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "docker",
          text: "部署与推理",
          prefix: "deployment/",
          collapsible: true,
          children: [
            { icon: "pattern", text: "量化", prefix: "01-量化/", children: "structure", collapsible: true },
            { icon: "docker", text: "vLLM 与 llama.cpp", prefix: "02-vLLM与llama-cpp/", children: "structure", collapsible: true },
            { icon: "collections", text: "批处理", prefix: "03-批处理/", children: "structure", collapsible: true },
            { icon: "concurrent", text: "并发", prefix: "04-并发/", children: "structure", collapsible: true },
            { icon: "rocket", text: "成本与延迟优化", prefix: "05-成本与延迟优化/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "photo",
          text: "多模态",
          prefix: "multimodal/",
          collapsible: true,
          children: [
            { icon: "photo", text: "视觉模型", prefix: "01-视觉模型/", children: "structure", collapsible: true },
            { icon: "imageLibrary", text: "图生图", prefix: "02-图生图/", children: "structure", collapsible: true },
            { icon: "movie", text: "语音", prefix: "03-语音/", children: "structure", collapsible: true },
            { icon: "tech", text: "视频理解 / 生成", prefix: "04-视频理解与生成/", children: "structure", collapsible: true },
            { icon: "framework", text: "多模态大模型", prefix: "05-多模态大模型/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "pattern",
          text: "NLP 基础",
          prefix: "nlp/",
          collapsible: true,
          children: [
            { icon: "basis", text: "分词", prefix: "01-分词/", children: "structure", collapsible: true },
            { icon: "pattern", text: "NER", prefix: "02-NER/", children: "structure", collapsible: true },
            { icon: "collections", text: "分类", prefix: "03-分类/", children: "structure", collapsible: true },
            { icon: "framework", text: "序列模型", prefix: "04-序列模型/", children: "structure", collapsible: true },
            { icon: "discover", text: "与 LLM 的对比", prefix: "05-与LLM的对比/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "sentinel",
          text: "评估与安全",
          prefix: "evaluation/",
          collapsible: true,
          children: [
            { icon: "rocket", text: "评测指标", prefix: "01-评测指标/", children: "structure", collapsible: true },
            { icon: "bug", text: "红队 / 对抗", prefix: "02-红队与对抗/", children: "structure", collapsible: true },
            { icon: "discover", text: "幻觉", prefix: "03-幻觉/", children: "structure", collapsible: true },
            { icon: "encryption", text: "隐私", prefix: "04-隐私/", children: "structure", collapsible: true },
            { icon: "sentinel", text: "合规", prefix: "05-合规/", children: "structure", collapsible: true },
          ],
        },
        {
          icon: "essay",
          text: "论文与前沿",
          prefix: "papers/",
          collapsible: true,
          children: [
            { icon: "essay", text: "重要论文笔记", prefix: "01-重要论文笔记/", children: "structure", collapsible: true },
            { icon: "framework", text: "新模型 / 新架构", prefix: "02-新模型与新架构/", children: "structure", collapsible: true },
            { icon: "discover", text: "行业动态", prefix: "03-行业动态/", children: "structure", collapsible: true },
          ],
        },
      ]
    },
    // {
    //   icon: "repair",
    //   text: "项目经验",
    //   prefix: "project",
    //   children: "structure",
    //   collapsible: true,
    // },
    {
      icon: "framework",
      text: "六、框架",
      collapsible: true,
      prefix: "framework/",
      children: [
        {
          icon: "spring",
          text: "Spring",
          prefix: "spring/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "springboot",
          text: "SpringBoot",
          prefix: "springboot/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "springcloud",
          text: "SpringCloud",
          prefix: "springcloud/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "netty",
          text: "Netty",
          prefix: "netty/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "mybatis",
          text: "MyBatis",
          prefix: "mybatis/",
          children: "structure",
          collapsible: true,
        }
      ]
    },
    {
      icon: "microservices",
      text: "七、微服务中间件",
      collapsible: true,
      prefix: "microservices/",
      children: [
        {
          icon: "docker",
          text: "Docker",
          prefix: "docker/",
          children: "structure", 
          collapsible: true,
        },
        {
          icon: "nacos",
          text: "Nacos",
          prefix: "nacos/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "rocketmq",
          text: "RocketMQ",
          prefix: "rocketmq/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "elasticsearch",
          text: "Elasticsearch",
          prefix: "elasticsearch/",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "dubbo",
          text: "Dubbo",
          prefix: "dubbo/",
          children: "structure", 
          collapsible: true,
        },
        {
          icon: "sentinel",
          text: "Sentinel",
          prefix: "sentinel/",
          children: "structure", 
          collapsible: true,
        }
      ]
    },
    {
      icon: "essay",
      text: "八、项目随笔",
      prefix: "projectessay/",
      collapsible: true,
      children: [
        {
          icon: "experience",
          text: "技术细节",
          prefix: "technicalDetails",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "project3",
          text: "实战项目",
          prefix: "practicalProjects/",
          collapsible: true,
          children: [
            {
              icon: "shortlink",
              text: "短链接",
              prefix: "shortlink",
              children: "structure",
              collapsible: true,
            },
            {
              icon: "imageLibrary",
              text: "智能图库",
              prefix: "imageLibrary",
              children: "structure",
              collapsible: true,
            },
            {
              icon: "logistics",
              text: "神领物流",
              prefix: "logistics",
              children: "structure",
              collapsible: true,
            },
            {
              icon: "oj",
              text: "刷题OJ平台",
              prefix: "oj",
              children: "structure",
              collapsible: true,
            },
            {
              icon: "onlineEducation",
              text: "学成在线",
              prefix: "onlineEducation",
              children: "structure",
              collapsible: true,
            },
            {
              icon: "flashSale",
              text: "秒杀系统",
              prefix: "flashSale",
              children: "structure",
              collapsible: true,
            } 
          ],
        },        
        {
          icon: "bug",
          text: "bug修复",
          prefix: "concurrent",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "rocket",
          text: "经验教训",
          prefix: "lessonsLearned",
          children: "structure",
          collapsible: true,
        },
        {
          icon: "scaffold",
          text: "脚手架",
          prefix: "scaffold",
          children: "structure",
          collapsible: true,
        }
      ]
    },
    {
      icon: "github",
      text: "九、开源推荐",
      prefix: "opensource/",
      collapsible: true,
      children: "structure"
    },
    {
      icon: "xiayu",
      text: "十、技术琐碎",
      collapsible: true,
      prefix: "rain/",
      children: [
        {
          icon: "clash",
          text: "Clash",
          prefix: "clash",
          collapsible: true,
          children: [
            "1.Openclash",
            "2.IPLeak",
            "3.LAN sharing",
            "4.Clash Verge Rev",
            "5.R2S install openwrt system",
            "6.Self-built nodes",
            "7.Various proxy issues",
            "8.DNS Leak",
            "9.Rule",
          ],
        },
        {
          icon: "encryption",
          text: "加解密",
          prefix: "encryption and decryption",
          collapsible: true,
          children: [
            "1.Symmetric encryption and symmetric encryption",
            "2.RSA"
          ],
        },
        "1.VPN",
        "2.Soft Router Prerequisite Home Network Communication",
        "3.Side Router"
      ]
    },
  ],
  "/life/": [
    {
      icon: "photo",
      text: "摄影",
      prefix: "photo",
      children: "structure",
      collapsible: true,
    },
    {
      icon: "movie",
      text: "读书与电影",
      prefix: "movie",
      children: "structure",
      collapsible: true,
    },
    {
      icon: "tech",
      text: "科技",
      prefix: "tech",
      children: "structure",
      collapsible: true,
    },
  ],
  "/about/" : [],
});
